name: Echidna Auto-publish
on:
  pull_request:
    paths: ["spec/**"]
  push:
    branches: [main]
    paths: ["spec/**"]
jobs:
  main:
    name: Echidna Auto-publish WD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: spec/index.html
          VALIDATE_LINKS: false
          VALIDATE_MARKUP: true
          ACTIONS_STEP_DEBUG: true
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/05/12-lws-minutes.html#f546
          W3C_BUILD_OVERRIDE: |
            specStatus: DNOTE
